- name: Install and run nginx
  hosts: localhost
  become: yes
  tasks:
   - name: Install nginx package
     ansible.builtin.package:
       name: nginx
       state: preesent
   - name: start nginx
     ansible.builtin.service:
       name: nginx
       state: started    