---
- name: Read Variable from inventory
  hosts: localhost
  become: yes 
  tasks:
   - name: Check Variables
     ansible.builtin.debug:
      msg: "I am learing {{Course}}, trainer is {{Trainer}}, and the duration is {{Duration}}"
