---
- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
     name: {{item}} # item is default keyword
     state: present 
    loop:
    - nginx
    - mysql
    - postfix
    - git


   